export enum CacheType {
  DID_DOCUMENT = "DID_DOCUMENT",
  JSON_LD_CONTEXT = "JSON_LD_CONTEXT",
  STATUS_LIST_CREDENTIAL = "STATUS_LIST_CREDENTIAL",
  VCT_METADATA = "VCT_METADATA",
  JSON_SCHEMA = "JSON_SCHEMA",
  TRUST_LIST = "TRUST_LIST",
  X509_CRL = "X509_CRL",
  ANDROID_ATTESTATION_CRL = "ANDROID_ATTESTATION_CRL",
  OPEN_ID_METADATA = "OPEN_ID_METADATA",
}
